// angularApp/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {

  loginForm: FormGroup;
  errorMessage: string = '';

  constructor(private fb: FormBuilder, private router: Router) {
    this.loginForm = this.fb.group({
      email: ['', Validators.required],
      password: ['', Validators.required]
    });
  }

  onSubmit() {
    if (this.loginForm.invalid) {
      this.errorMessage = 'Please fill in all fields';
      return;
    }

    const { email, password } = this.loginForm.value;

    fetch('http://localhost:3000/users/login', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password })
    })
    .then(async res => {
      if (res.ok) {
        const data = await res.json();
        localStorage.setItem('token', data.token);
        this.router.navigate(['/']);
      } else {
        this.errorMessage = 'Invalid credentials';
      }
    })
    .catch(err => {
      console.error(err);
      this.errorMessage = 'Something went wrong';
    });
  }
}

<h2>Login</h2>

<form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
  <label>
    Email:
    <input type="text" formControlName="email" />
  </label>
  <br/>
  <label>
    Password:
    <input type="password" formControlName="password" />
  </label>
  <br/><br/>
  <button type="submit">Login</button>
</form>

<p style="color:red">{{ errorMessage }}</p>

// reactApp/src/components/Login.jsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'

function Login(props) {
  const [email, setEmail] = useState('')
  
  const [password, setPassword] = useState('')
  const [confirmPassword, setCOnfirmPassword] = useState('')
  
  const [error, setError] = useState('')
  const navigator = useNavigate()

  const handleSubmit = async() => {
    console.log("Login button clicked", email, password)
    if (!email || !password) {
      setError('Please fill all the fields.')
    }

    const res = await fetch('http://localhost:3000/users/login', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: email, password: password }),
   });
   const data = await res.json();
   
   if (res.status === 200) {
    localStorage.setItem('token', data.token)
    navigator('/')
   }
   else {
    setError('Something went wrong.')
   }
  }

  return (
    <>
      <div>Login page</div>
      <p>Enter your email</p>
      <input name='email' value={email} onChange={e => setEmail(e.target.value)} />

      <p>Enter your password</p>
      <input type='password' name='password' value={password} onChange={e => setPassword(e.target.value)} />
      <br/>
      <br/>
      <button onClick={handleSubmit}> Login </button>
      <p> {error} </p>
    </>
  )
}

export default Login
